// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Surgenius.Infrastructure.Data.Context;

#nullable disable

namespace Surgenius.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Surgenius.Domain.Models.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaskPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScanID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TumorSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TumorStage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScanID")
                        .IsUnique();

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("Surgenius.Domain.Models.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("Surgenius.Domain.Models.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScanPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaseID");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("Surgenius.Domain.Models.ThreeDModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LiverModelPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScanID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TumorModelPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScanID")
                        .IsUnique();

                    b.ToTable("ThreeDModels");
                });

            modelBuilder.Entity("Surgenius.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Surgenius.Domain.Models.AnalysisResult", b =>
                {
                    b.HasOne("Surgenius.Domain.Models.Scan", "Scan")
                        .WithOne("AnalysisResult")
                        .HasForeignKey("Surgenius.Domain.Models.AnalysisResult", "ScanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("Surgenius.Domain.Models.Case", b =>
                {
                    b.HasOne("Surgenius.Domain.Models.User", "User")
                        .WithMany("Cases")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Surgenius.Domain.Models.Scan", b =>
                {
                    b.HasOne("Surgenius.Domain.Models.Case", "Case")
                        .WithMany("Scans")
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Surgenius.Domain.Models.ThreeDModel", b =>
                {
                    b.HasOne("Surgenius.Domain.Models.Scan", "Scan")
                        .WithOne("ThreeDModel")
                        .HasForeignKey("Surgenius.Domain.Models.ThreeDModel", "ScanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("Surgenius.Domain.Models.Case", b =>
                {
                    b.Navigation("Scans");
                });

            modelBuilder.Entity("Surgenius.Domain.Models.Scan", b =>
                {
                    b.Navigation("AnalysisResult");

                    b.Navigation("ThreeDModel");
                });

            modelBuilder.Entity("Surgenius.Domain.Models.User", b =>
                {
                    b.Navigation("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
